pipeline {
    agent any

    stages {

        stage('Create .env') {
            steps {
                sh '''
                echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" > .env
                echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> .env
                echo "MYSQL_USER=$MYSQL_USER" >> .env
                echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
                '''
            }
        }

        stage('Copy application.yml') {
            steps {
                sh '''
                mkdir -p backend/wakeupmate/src/main/resources
                cp /var/jenkins_home/secure-configs/application.yml backend/wakeupmate/src/main/resources/application.yml
                '''
            }
        }

        stage('Gradle Build') {
            steps {
                dir('backend/wakeupmate') {
                    sh './gradlew clean build'
                }
            }
        }

        stage('Compose Down') {
            steps {
                sh 'docker compose -f backend/wakeupmate/compose.yaml down'
            }
        }

        stage('Compose Up (Rebuild)') {
            steps {
                sh 'docker compose -f backend/wakeupmate/compose.yaml up -d --force-recreate'
            }
        }
    }
}