pipeline {
    agent any

    environment {
        COMPOSE_PATH = "./"
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/gitFILO/wakeupmate.git'
            }
        }

        stage('Build & Deploy') {
            steps {
                script {
                    sh """
                    docker-compose -f ${COMPOSE_PATH}/docker-compose.yml down
                    docker-compose -f ${COMPOSE_PATH}/docker-compose.yml up -d --build
                    """
                }
            }
        }
    }
}