input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["spring-logs"]
    group_id => "logstash"
    codec => plain
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
